# Generated by Django 6.1.1 on 2026-09-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
                ('c_image', models.ImageField(null=True, upload_to='media/course_img')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
                ('department_head', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, null=True)),
                ('marks', models.PositiveIntegerField(null=True)),
                ('grade', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, null=True)),
                ('s_image', models.ImageField(null=True, upload_to='media/student_img')),
                ('admission_date', models.DateField(null=True)),
                ('course_name', models.CharField(max_length=150, null=True)),
                ('course_fee', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.IntegerField(null=True)),
            ],
        ),
    ]
